### ISSUE TITLE
render async when scrolling down to some point

### ISSUE THREAD

**Issue by b-solution** [nikolalsvk/render_async#102]
hi.
I want to use render async in some cases where the user try to scroll down, so i will show the content.
is it possible to make this?
thanks

**Comment by nikolalsvk** [comment]
Hey, @bilel-kedidi! Thanks for submitting the issue!

There's a suggestion to implement this in https://github.com/renderedtext/render_async/issues/34, does this sound like something you'd like to have?

**Comment by nikolalsvk** [comment]
I'll close this issue since it seems to be a duplicate of https://github.com/renderedtext/render_async/issues/34. Feel free to reopen it if you think it's not!
