### ISSUE TITLE
preventDefault() in toggle code interferes with other UI functionality

### ISSUE THREAD

**Issue by vanboom** [nikolalsvk/render_async#109]
I have a tabbed interface where I would like to kick off the render async when the user selects a tab.  The tab system is built using a radio and HTML/CSS only.

I can attach render_async toggle selector to the ID of the radio button that controls the tab switching, but preventDefault() is keeping the default radio behavior from happening. 

I am proposing that the preventDefault() be removed from _request_jquery.js.erb:105.  So far in my app I have not found any negative ramifications of doing so.  

Thanks for all you guys do on this gem.

**Comment by nikolalsvk** [comment]
Closed in https://github.com/renderedtext/render_async/pull/110

**Comment by nikolalsvk** [comment]
This is resolved in [2.1.6](https://github.com/renderedtext/render_async/releases/tag/2.1.6). Let's reopen it in case it's not!
