### ISSUE TITLE
Render_async on header

### ISSUE THREAD

**Issue by deikka** [nikolalsvk/render_async#115]
Hi! 

I am trying to load a partial in the header and it doesn't load. If I put the code in the view, it does.

Header partial: 
`<%= render_async notifications.notifications_count_path %>`

Controller (notifications engine, maybe this is not ok):

`	def notifications_count
		@notif_count = Notification.unread_count(current_user)
		render partial: 'layouts/notifications_count'
	end
`
Inside my routes:

`	Notifications::Engine.routes.draw do
		get :notifications_count, controller: :notifications
	end
`

Am I doing something wrong? 

Thanks in advance!

**Comment by nikolalsvk** [comment]
Hey, @deikka, thanks for submitting an issue! Did you try adding `<%= content_for :render_async %>` inside `<header>` tag?

**Comment by deikka** [comment]
wow, that's fast! Thanks for the tip, now it's working :)
The conten_for was in application.html.erb inside head tag. 

thanks again!!
