### ISSUE TITLE
Duplication of injected JS for nested async templates

### ISSUE THREAD

**Issue by vanboom** [nikolalsvk/render_async#116]
I have a tabbed UI where a CREATE action can add tabs.  The tabs are dynamically loaded using render_async when the user clicks on the tab label.  Consider something like this...

![targetprocess-screen-capture (6)](https://user-images.githubusercontent.com/251706/82076539-9b720d00-96a3-11ea-86b1-0a8ea7ad1ffc.png)

Each tab is loaded asynchronously, so the view layout contains:  
```haml
= content_for(:render_async)
```
However, because the CREATE function can add a new tab to the UI, the asynchronous view partial also contains:  
```haml
= content_for(:render_async)
```
This is causing duplication of the injected Javscript when the view is rendered because it is being injected at the layout level and within the partial for each tab. 

**Possible solution:**  what if the `render_async` method accepted an option to specify the content tag?   This would provide control over where the injected Javascript would go.  Of course, the option would default to `:render_async` for backward compatibility.  I will experiment with this on my fork and offer a PR if I can get something working.

**Comment by nikolalsvk** [comment]
This should now be possible to avoid with [2.1.7](https://github.com/renderedtext/render_async/releases/tag/2.1.7) version! Big thanks to @vanboom for making a feature of [customizing content_for name](https://github.com/renderedtext/render_async#customizing-the-content_for-name) a reality 🍰  🎉 !

BTW, there is also a [Discord channel](https://discord.gg/SPfbeRm) where you can post suggestions and get help quickly. I'd be happy to see you there as well. 💚
