### ISSUE TITLE
Start polling immediately option when toggle is specified

### ISSUE THREAD

**Issue by vanboom** [nikolalsvk/render_async#118]
Suggestion:  provide an option to start polling immediately even when a toggle is provided.   The current behavior is to poll immediately when a toggle is not present, but wait for the toggle when the toggle option is used.  

This would support the use case where we want to start polling immediately on page load but provide the user the capability to toggle the polling OFF.  Thanks for your consideration.

**Comment by nikolalsvk** [comment]
Hey, @vanboom. This issue got resolved in the new [2.1.8 version](https://github.com/renderedtext/render_async/releases/tag/2.1.8). Let me know if it works for you.

Cheers 🍻
