### ISSUE TITLE
Idea: only fire the AJAX request on scroll (Lazy Partials)

### ISSUE THREAD

**Issue by feliperaul** [nikolalsvk/render_async#122]
I'm sorry if this gem already does this, but I couldn't find it in the documentation.

The idea is: go one step further in optimizing the page load, and have `lazy` partials, just like we have lazy images.

Using the Intersection Observer API (https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API), we can fire the AJAX request for the partial only if the user scrolls down and gets near the partial placeholder.

Imagine a blog posts comment section. If we use something like `<%= render_async comment_stats_path, lazy: true %>`, the javascript could use the IntersectionObserver API to only fire that request some X pixels before the user reaches the partial.

What do you guys think? :)

**Comment by nikolalsvk** [comment]
Hey @feliperaul, thanks for submitting an issue!

There is a similar issue here https://github.com/renderedtext/render_async/issues/34, I'll close this one in the favor of it :)

You can add your ideas or even try it out and post progress there!
