### ISSUE TITLE
Event driven reloads.

### ISSUE THREAD

**Issue by davissp14** [nikolalsvk/render_async#126]
So I am looking to achieve to what I can best describe as an "event driven reload".

Example Use-case:

A list of students is rendered on page load and a button is presented to the end-user that will allow them to refresh that list.

-- 

I do see that there's `toggle` functionality available, however, the event selector seems to gate-keep the initial render.

Is there currently any path for rendering on page load and leveraging events to trigger subsequent renders?

**Comment by davissp14** [comment]
Related, or perhaps a duplicate request:  https://github.com/renderedtext/render_async/issues/121

**Comment by nikolalsvk** [comment]
Hey, @davissp14, thanks for opening the issue. 

Unfortunately, there's no way to render on page load when using the toggle feature. Adding this is the next thing I am going to work on.

You could get some ideas [the controlled polling example](https://github.com/renderedtext/render_async#controlled-polling). But I think it's best to wait for the new feature that will allow you to do so. If you have any ideas, PRs are appreciated.

**Comment by nikolalsvk** [comment]
Hey, @davissp14. I recently added a feature where you can dispatch an event with the name "refresh" on the render_async container. There is more information in the [2.1.8 release](https://github.com/renderedtext/render_async/releases/tag/2.1.8) and [docs here](https://github.com/renderedtext/render_async#refreshing-the-partial). Is this something you were looking for?

Let me know if it works for you. In the meantime, I will close the issue. Looking forward to your response, cheers 🍻
