### ISSUE TITLE
Add Support for Turbo

### ISSUE THREAD

**Issue by Mbuckley0** [nikolalsvk/render_async#140]
Recently rails added in a replacement for turbolinks called turbo. It works in a similar way to turbolinks except now it has events like `turbo:load` instead of `turbolinks:load`. If you're happy for me to do so I can do up a PR adding turbo in as a configuration option just like turbolinks is.

**Comment by nikolalsvk** [comment]
Hey, @Mbuckley0, thanks for opening an issue.

> If you're happy for me to do so I can do up a PR adding turbo in as a configuration option just like turbolinks is.

Sure, please submit a PR and I will check it out, thank you.

**Comment by Mbuckley0** [comment]
@nikolalsvk I've added in a PR now. https://github.com/renderedtext/render_async/pull/141

**Comment by nikolalsvk** [comment]
I just released this in [2.1.9 version](https://github.com/renderedtext/render_async/releases/tag/2.1.9). 

Thanks a lot, @Mbuckley0
