### ISSUE TITLE
Add readme note about use with turbolinks?

### ISSUE THREAD

**Issue by colinxfleming** [nikolalsvk/render_async#26]
hey @nikolalsvk , spent some time a few weeks ago on getting a `render_async` div to work cleanly with turbolinks, which wound up requiring a somewhat specific incantation. It seems like it might be a pretty common use case given that turbolinks is part of the rails standard, so I thought I might pay it forward and add a recipe for it to the readme, but wanted to check with you first to make sure that was cool.

If you'd rather not feel free to close this issue, otherwise let me know! 💯

**Comment by nikolalsvk** [comment]
Hey @colinxfleming, thanks for raising this issue!

I'm totally fine with you adding a recipe for working with Turbolinks :)

Feel free to add it, it will certanly help some people trying to set it up.
