### ISSUE TITLE
Idea: Jquery or no-jQuery, depending on config

### ISSUE THREAD

**Issue by elsurudo** [nikolalsvk/render_async#38]
There is no point rendering both the jQ, and non-jQ JS, when in reality only one will be used. IMO it would make sense to simply make this a config var on the server-side. Default should be vanilla JS, I suppose?

**Comment by nikolalsvk** [comment]
> There is no point rendering both the jQ, and non-jQ JS, when in reality only one will be used.

I agree 100% 👍 

> Default should be vanilla JS

I'd rather use jQuery beacuse vanilla JS code has issues with making script tag to work, see https://github.com/renderedtext/render_async/issues/30

**Comment by nikolalsvk** [comment]
Made the gem render Vanilla JS be default in [the new release](https://github.com/renderedtext/render_async/releases/tag/2.0.0) :)

Thanks for the idea @elsurudo! 🍺
