### ISSUE TITLE
Add CHANGELOG.md

### ISSUE THREAD

**Issue by nikolalsvk** [nikolalsvk/render_async#44]
Include CHANGELOG.md file in the repo where users can easily go through changes. But also, keep the Releases tab up-to-date.

**Comment by gil27** [comment]
Hello @nikolalsvk, if you don't mind, I would like to do it. =)

**Comment by nikolalsvk** [comment]
Hey @gil27, thanks for wanting to help out :) :cake: 

You can use the [Releases](https://github.com/renderedtext/render_async/releases) tab to form the CHANGELOG.md

Ping me if you need any help :)

**Comment by nikolalsvk** [comment]
Closed with https://github.com/renderedtext/render_async/pull/69
