### ISSUE TITLE
Event dispatch does not work on IE11

### ISSUE THREAD

**Issue by fschwahn** [nikolalsvk/render_async#45]
Creating new events using `new Event("...")` does not work in IE11 ("Object doesn't support this action").

I fixed this "problem" in my app by overriding the render_async partial, and using jQuery to trigger the event (ie. `$(document).trigger("<%= event_name %>");`). There [are other workarounds](https://stackoverflow.com/a/32889608/891458), however these are already [deprecated in newer browsers](https://developer.mozilla.org/en-US/docs/Web/API/Event/initEvent).

I don't think there is anything to be done in this gem, as IE11 is already pretty old. Just leaving this here if somebody runs into this problem.

**Comment by malaiyappanprisam** [comment]
$(document).trigger("<%= event_name %>"); - where you called this code?

**Comment by fschwahn** [comment]
Around here I think:

https://github.com/renderedtext/render_async/blob/master/app/views/render_async/_request.js.erb#L8

**Comment by nikolalsvk** [comment]
Hey @fschwahn @malaiyappanprisam, I managed to fix event handling for the IE (what a turnaround from being labeled as a wontfix 😄)

If you want, you can try it out in the [new 2.0.0 version](https://github.com/renderedtext/render_async/releases/tag/2.0.0) of the gem :) 

https://rubygems.org/gems/render_async/versions/2.0.0

**Comment by fschwahn** [comment]
Great, thanks for fixing this!
