### ISSUE TITLE
Retry/failure event

### ISSUE THREAD

**Issue by krainboltgreene** [nikolalsvk/render_async#46]
So we have a large amount of data we want from the server, so we do this:

  - Get the total count of the data
  - Create "pages"
  - `render_async_cache` for each page
  - View cache the partial based on the async cache key: `cache(render_async_cache_key) { ... }`
  - View cache based on the collection `cache(records)`
  - View cache the individual `cache(record)`

So sometimes it takes a long time to load a an async partial and those requests timeout, but we can safely retry those requests and each time they'll get smaller.

I would love to have an option for `render_async*()` that tells the javascript to retry on failure (infinitely, or n times with backoff). Thoughts?

**Comment by nikolalsvk** [comment]
I like the idea 👍 

Do you have any thoughts on how we could do this?

**Comment by krainboltgreene** [comment]
I'll experiment today.

**Comment by justinthiele** [comment]
In the meantime, if there is a timeout, how do I go about showing an error message in the view? Currently it silently fails and nothing renders to the view. Appreciate any tips on this.

Thanks for this gem, super useful and easy to implement 😄

**Comment by nikolalsvk** [comment]
Hey @justinthiele,

Maybe you can try to [emit an event](https://github.com/renderedtext/render_async#passing-in-an-event-name) when your request is finished. 

Can you tell me how that works out? If it's not working out, we can create a new feature that let's you do stuff on request error/timeout.

**Comment by justinthiele** [comment]
Thanks for the reply @nikolalsvk :)

I tried emitting an event like in the documentation but the event gets triggered the same whether the operation was successful or not, so I'm still not sure how to know when to show the error message. I don't know much javascript, so it's entirely plausible that there is any easy solution that I'm not aware of, haha.

**Comment by nikolalsvk** [comment]
@justinthiele hmm, I can't come up with a quick fix for this 🤔 

Could you maybe open another issue for this and I'll implement it? :)

**Comment by justinthiele** [comment]
Ok, thanks @nikolalsvk! I just created [Issue #51](https://github.com/renderedtext/render_async/issues/51) for this.

Apologies for hijacking this thread :)

**Comment by nikolalsvk** [comment]
Thanks for opening the issue @justinthiele 🍺

**Comment by nikolalsvk** [comment]
Hey @krainboltgreene, I've added error handling to the gem, maybe that will help out in your case a bit :)

You can read about it in [the new release](https://github.com/renderedtext/render_async/releases/tag/2.0.0)!

BTW, are you still interested in the retry mechanism for `render_async`?

**Comment by televisedBow** [comment]
> render_async



> Hey @krainboltgreene, I've added error handling to the gem, maybe that will help out in your case a bit :)
> 
> You can read about it in [the new release](https://github.com/renderedtext/render_async/releases/tag/2.0.0)!
> 
> BTW, are you still interested in the retry mechanism for `render_async`?

I think an option to retry X amount of times would be extremely useful. I just started using this gem and noticed that about 10% of the time the page never refreshes. It would be a much better user experience to just retry this in the background instead of telling them to refresh the page.

**Comment by nikolalsvk** [comment]
Hey @televisedBow and @krainboltgreene,

I've just implemented this feature in https://github.com/renderedtext/render_async/pull/76. I explained how to use it in the [README](https://github.com/renderedtext/render_async/blob/7f7d885e981f3022af712384efb376238b3808d6/README.md#retry-on-failure).

Also, I've released [2.1.0 version](https://github.com/renderedtext/render_async/releases/tag/2.1.0) where you can try it out if you want 🎉

**Comment by ljesus** [comment]
Thanks for your work. Is there a way to set a retry interval, instead of firing the requests right away?

**Comment by nikolalsvk** [comment]
Hey @ljesus, thank you for commenting!

There's no option to set a retry interval unfortunately :( right now requests are fired immediately.

If you want, you can open a new issue because this seems like an additional feature we could add to the retry mechanism :)
