### ISSUE TITLE
Ability to show an error message if the request fails

### ISSUE THREAD

**Issue by justinthiele** [nikolalsvk/render_async#51]
Per our discussion on [Issue #46](https://github.com/renderedtext/render_async/issues/46), it'd be great to have the ability to show an error message if the request fails (timeout, 404, 500, etc).

Thanks for all of your work on this gem @nikolalsvk!

**Comment by nikolalsvk** [comment]
Hey @justinthiele, managed to get this feature into the gem!

If you're still interested, I'd be more than thankful if you could try it out in [the new release](https://github.com/renderedtext/render_async/releases/tag/2.0.0) :)

https://rubygems.org/gems/render_async/versions/2.0.0

**Comment by justinthiele** [comment]
Awesome, thanks so much Nikola! I'll update soon :)
