### ISSUE TITLE
Async content node weirdly dissapearing

### ISSUE THREAD

**Issue by filipewl** [nikolalsvk/render_async#53]
Hello there!

I've started using this gem for creating a dashboard and ran into a strange issue. The container is being removed somehow, instead of having its content replaced with what comes from the AJAX's response. Take a look:

![brokz70rum](https://user-images.githubusercontent.com/381395/38443322-affa7e9c-39c1-11e8-87cf-e7233fa39170.gif)

My structure is pretty straightforward:

```erb
# view.html.erb
<%= render_async foo_path do %>
  Loading number of logins...
<% end %>
```

```erb
# _partial.html.erb
<h3>Number of logins:</h3> <%= @logins_count %>
```

Weirdly enough, I had it working just fine after a few tries. Then as I continued with other changes, it stopped working again. I even reverted to a commit I thought I had it working and it just didn't work. 
`¯\_(ツ)_/¯`

I can't pinpoint exactly what could be going wrong, any guess?

Thanks for the gem! I first got to know it by the Semaphore's article and knew I would be useful any time I were to work with async loading partials with Rails. :)

**Comment by filipewl** [comment]
I got it working intermittently:

![x742a98dxx](https://user-images.githubusercontent.com/381395/38444497-cea54aee-39c5-11e8-86c1-1d955c4b85f0.gif)

One thing that caught my attention is the difference in DevTool's preview for the response.

Application-wise, everything is and seems the same:

```sql
Started GET "/dashboard?utf8=%E2%9C%93&dashboard_form%5Brange_key%5D=last_4_weeks&commit=Create+Form" for ::1 at 2018-04-06 18:09:00 -0300
Processing by DashboardsController#show as HTML
  Parameters: {"utf8"=>"✓", "dashboard_form"=>{"range_key"=>"last_4_weeks"}, "commit"=>"Create Form"}
  Rendering dashboards/show.html.erb within layouts/application
  Rendered /.rvm/gems/ruby-2.3.3@project/gems/render_async-1.2.0/app/views/render_async/_request.js.erb (0.7ms)
  Rendered /.rvm/gems/ruby-2.3.3@project/gems/render_async-1.2.0/app/views/render_async/_render_async.html.erb (9.1ms)
  Rendered dashboards/show.html.erb within layouts/application (16.8ms)
  Rendered application/_header.html.erb (2.3ms)
Completed 200 OK in 206ms (Views: 202.0ms | ActiveRecord: 0.0ms)

# First request:

Started GET "/dashboard/queries/logins_count?range_key=last_4_weeks" for ::1 at 2018-04-06 18:09:01 -0300
Processing by Dashboard::Queries::LoginsCountController#call as */*
  Parameters: {"range_key"=>"last_4_weeks"}
   (199.1ms)  SELECT COUNT(*) FROM "customers" WHERE ("customers"."..." BETWEEN $1 AND $2)  [["...", Sun, 04 Mar 2018], ["...", Sat, 31 Mar 2018]]
  Rendered dashboard/queries/logins_count/_call.html.erb (0.4ms)
Completed 200 OK in 207ms (Views: 6.5ms | ActiveRecord: 199.1ms)


Started GET "/dashboard?utf8=%E2%9C%93&dashboard_form%5Brange_key%5D=last_month&commit=Create+Form" for ::1 at 2018-04-06 18:09:06 -0300
Processing by DashboardsController#show as HTML
  Parameters: {"utf8"=>"✓", "dashboard_form"=>{"range_key"=>"last_month"}, "commit"=>"Create Form"}
  Rendering dashboards/show.html.erb within layouts/application
  Rendered /.rvm/gems/ruby-2.3.3@project/gems/render_async-1.2.0/app/views/render_async/_request.js.erb (0.6ms)
  Rendered /.rvm/gems/ruby-2.3.3@project/gems/render_async-1.2.0/app/views/render_async/_render_async.html.erb (8.3ms)
  Rendered dashboards/show.html.erb within layouts/application (17.4ms)
  Rendered application/_header.html.erb (2.2ms)
Completed 200 OK in 253ms (Views: 249.7ms | ActiveRecord: 0.0ms)

# 2nd request:

Started GET "/dashboard/queries/logins_count?range_key=last_month" for ::1 at 2018-04-06 18:09:08 -0300
Processing by Dashboard::Queries::LoginsCountController#call as */*
  Parameters: {"range_key"=>"last_month"}
   (265.8ms)  SELECT COUNT(*) FROM "customers" WHERE ("customers"."..." BETWEEN $1 AND $2)  [["...", Thu, 01 Mar 2018], ["...", Sat, 31 Mar 2018]]
  Rendered dashboard/queries/logins_count/_call.html.erb (0.5ms)
Completed 200 OK in 275ms (Views: 7.6ms | ActiveRecord: 265.8ms)
```

**Comment by filipewl** [comment]
I debugged this a little bit further and I was able to fix it by setting the `dataType` to `'html'` in the [$.ajax call](https://github.com/renderedtext/render_async/blob/6929771f1e266f5cadec20939316c0d290f9ec12/app/views/render_async/_request.js.erb#L4).

In the failure case, the [`response`](https://github.com/renderedtext/render_async/blob/6929771f1e266f5cadec20939316c0d290f9ec12/app/views/render_async/_request.js.erb#L4) returned was a [jqXHR object](https://api.jquery.com/jQuery.ajax/#jqXHR), instead of the expected HTML. It failed [replacing the HTML](https://github.com/renderedtext/render_async/blob/6929771f1e266f5cadec20939316c0d290f9ec12/app/views/render_async/_request.js.erb#L5). It did contain the HTML I wanted inside `response.responseText` though:
![01](https://user-images.githubusercontent.com/381395/38525030-252cba88-3c27-11e8-84ec-0531a073ea42.png)

After patching the `$.ajax` call, I got this proper response:
![02](https://user-images.githubusercontent.com/381395/38525073-559cfdfe-3c27-11e8-91d8-c16fa046ae5d.png)
(note the `this.dataType: 'html'`/`this.dataTypes: ['text', 'html']`)

Is it desirable to have `dataType` set to `'html'`? Aren't we always expecting an HTML here?

Or, would it be possible to configure this param like in #52?

**Comment by nikolalsvk** [comment]
Hey @filipewl, thanks for submitting an issue and posting about detailed debugging 🙇 

This is really a strange issue, didn't happen to me before. I'm just interested - are you doing something different in the controllers depending on the `range_key` param? More specifically, I'm interested in how are you rendering the response inside your controller.

> Is it desirable to have dataType set to 'html'? Aren't we always expecting an HTML here? Or, would it be possible to configure this param like in #52?

I'm not sure about `dataType` being set to `html` always. It would probably be the best to make it configurable as you said.

**Comment by filipewl** [comment]
> This is really a strange issue, didn't happen to me before. 

Yeah, I don't think this should be happening with anybody else. 😕 

> are you doing something different in the controllers depending on the range_key param? More specifically, I'm interested in how are you rendering the response inside your controller.

Here's what I have:

```ruby
# app/controllers/dashboard/queries/foo_count_controller.rb

module Dashboard
  module Queries
    class FooCountController < ApplicationController
      def call
        respond_to do |format|
          format.js do
            @count = Dashboard::Queries::FooCount.call range
			# The problem continues even if I do not use `Dashboard::Queries::FooCount.call range` at all:
			# @count = 1

            render partial: 'call'
          end
        end
      end

      private

      def range
		# Return a pre-defined date range.
        Dashboard::Range.for params[:range_key]
      end
    end
  end
end
```

```erb
<%# app/views/dashboard/queries/logins_count/_call.html.erb %>

<h3>Number of logins:</h3> <%= @count %>
```

As I noted, even running the action without calling any external code also doesn't work. I also tried commenting out the `respond_to/format.js` blocks.

I'm starting to think that maybe it's a problem with the response's content type returned by Rails? I've tried setting the content type manually without avail, but maybe I'm doing it incorrectly. I'm on Rails 5.0.0.1, by the way.

Or with `$.ajax` `dataType`'s [intelligent guess](https://api.jquery.com/jQuery.ajax/#data-types)? It seems to be that Rails is returning a content type of `["text", "script"]`, when what I needed is `["text", "html"]`.

> I'm not sure about dataType being set to html always. It would probably be the best to make it configurable as you said.

I agree. Maybe it could break somebody else use if we hardcode it.

Do you need help reviewing #52? 
I'll try to come up with a new PR to optionally set `$.ajax`'s `dataType` if that's okay.

Thanks for the help!

**Comment by filipewl** [comment]
Aaaah, I seem to have figured out one of the mysteries. 

It seems Chrome was HTTP caching my requests, so I wasn't noticing some of changes I had applied to my action. I checked the "Disable cache" option in the Dev Tools and I'm getting a better picture now.

The error happens when I wrap my action/render inside the `respond_to/format.js` blocks. Rails prints `text/javascript` for `response.content_type` inside the action. `$.ajax` then interprets it as a `text/script` and fails to replace the content.

When I remove the `respond_to/format.js` blocks, Rails prints `nil` for `response.content_type`, `$.ajax` interprets it as a `text/html` and the content is successfully replaced (I couldn't notice it was working because I had a bugged response cached 😓).

I managed to get it working, without patching `render_async`, with `respond_to/format.js` blocks, by changing `response.content_type = 'text/html'` inside it!

For my case, the `respond_to/format.js` blocks matter because I don't want the users opening the path in the browser. Only if a `JS` format is requested.

Could you try using `respond_to/format.js` to see if that's really the problem, please?

Using `respond_to/format.js` can be common in some Rails apps, so it'd be better if the gem could cover these use cases seamlessly (without the need to manually change the `response.content_type`).

**Comment by nikolalsvk** [comment]
Thank you @filipewl for the detailed responses, it will sure mean a lot to someone encountering similar issues.

Good news that you managed to make it work. If you want to make the solution more elegant, maybe you can try to do:
```
render partial: 'call', content_type: 'text/html'
```

If this works and looks good to you, maybe you can add a recipe on the project README about it (you'll definitely earn a place in the list of contributors for that!). The recipe would describe the problem that happens with browser caching HTTP requests with `respond_to` and `format.js` combination, and the solution that covers it.

Let me know how this sounds to you 🍺

**Comment by filipewl** [comment]
That's more elegant, indeed! I'll use that, thanks.

I'll submit a PR with that change to the README soon then.
😊 

Cheers!
