### ISSUE TITLE
Render multiple partials in one html view

### ISSUE THREAD

**Issue by pbasl** [nikolalsvk/render_async#55]
Hi;
I started to use your gem to render ads in my application. I have multiple ads in the page, so I used render_async multiple times However, only one of them shows up at the end. Is this a limitation or is there something I am missing out?
Thanks

**Comment by nikolalsvk** [comment]
Hi @pbasl, thanks for submitting an issue. Can you maybe post a code snippet of how you're using render_async in the .html.erb file your action is rendering? It would help a lot. 

Also, try [nested render_async guide](https://github.com/renderedtext/render_async#nested-async-renders) if you're nesting render_async calls.

**Comment by pbasl** [comment]
Thanks for your reply. Unfortunately, I deleted everything render_async related from my code. However, I will try to reproduce and will update once code is ready again.

**Comment by pbasl** [comment]
Hi @nikolalsvk ;
While trying to duplicate the issue, I got it working. May be I had a mistake in implementation the first time.
But I want to confirm one thing though; where should 
    `<%= content_for :render_async %>` 
be put? body or head of application.html.erb layout file??
Thanks

**Comment by nikolalsvk** [comment]
`<%= content_for :render_async %>` should be put into the body part of the application.html.erb, I'll add the info to the README.

**Comment by pbasl** [comment]
Thanks & great gem by the way.
