### ISSUE TITLE
How can I update my view with jquery interval?

### ISSUE THREAD

**Issue by abidiqbalk** [nikolalsvk/render_async#67]
I want to constantly update my partial rendering for showing latest feed after 5 minutes interval. How can I do as using jquery getscript with the specified URL only works in the background and partial on the front side never gets updated?

Thanks

**Comment by nikolalsvk** [comment]
Hey @abidiqbalk, thanks for opening the issue! Can't think of the quick fix for this, I'd have to expand the codebase to support it. 

I'd have to add a code that supports polling of the path you provide. Is it the polling feature you're interested in? It would basically call the path you provided to render_async every N seconds for M times.

**Comment by abidiqbalk** [comment]
@nikolalsvk exactly this is what I want "call the path you provided to render_async every N seconds for M times"

**Comment by nikolalsvk** [comment]
Awesome, I'll see to implement this, sounds like an interesting feature that many users can benefit from.

Also, it looks like it's linked to https://github.com/renderedtext/render_async/issues/46

**Comment by abidiqbalk** [comment]
@nikolalsvk would love to use this feature and give it a  🌟

**Comment by rafaelgoulart** [comment]
I'd love to see this feature as well!

**Comment by nikolalsvk** [comment]
Hey y'all,

I've just released this feature in [2.1.0 version](https://github.com/renderedtext/render_async/releases/tag/2.1.0)

Try it out if you can and let me know how it works :)

**Comment by ljesus** [comment]
Thanks @nikolalsvk . Is there a way to stop the polling if needed?

**Comment by nikolalsvk** [comment]
No problem @ljesus. There's no way to stop the polling right now, we should add it definitely!

You can create a new issue with this topic and we could implement it :)
