### ISSUE TITLE
Please add a CHANGELOG

### ISSUE THREAD

**Issue by alainravet** [nikolalsvk/render_async#68]
3 releases in 1 day. What happened?
Too many commits to review -> I won't upgrade right now.

This project needs a changelog.

**Comment by filipewl** [comment]
It's already being worked on, see #44.

**Comment by nikolalsvk** [comment]
Hey @alainravet, sorry about this. You can check out the [Releases](https://github.com/renderedtext/render_async/releases) tab where I describe everything that was changed :)

We'll have a CHANGELOG.md hopefully soon!

**Comment by nikolalsvk** [comment]
Here's the changelog PR https://github.com/renderedtext/render_async/pull/69
