### ISSUE TITLE
undefined method `configuration' for RenderAsync:Module (NoMethodError)

### ISSUE THREAD

**Issue by jaswinder97** [nikolalsvk/render_async#71]
I was trying to change configuration to load query instead of Vanilla at application.rb using:

`RenderAsync.configuration.jquery = true`

But getting this error

**Comment by nikolalsvk** [comment]
Hey @jaswinder97, thanks for submitting the issue.

Did you maybe try other [configuration](https://github.com/renderedtext/render_async#configuration) approach?

```rb
RenderAsync.configure do |config|
  jquery = true # This will render jQuery code, and skip Vanilla JS code
end
```

**Comment by jaswinder97** [comment]
@nikolalsvk Yes I tried it with both ways and also with different versions.

**Comment by nikolalsvk** [comment]
Hmm, that is really wierd @jaswinder97 :(

I have integration tests that verify that jQuery version works. Could you share some more details about your project? Maybe something is clashing with render_async.

**Comment by nikolalsvk** [comment]
Are you still encountering this issue @jaswinder97? If yes, feel free to post a comment here with more details and I'll reopen the issue.
