### ISSUE TITLE
Bundler compatibility

### ISSUE THREAD

**Issue by n-rodriguez** [nikolalsvk/render_async#73]
Hi!
Bundler 2.0 is out :) https://bundler.io/blog/2019/01/03/announcing-bundler-2.html

But render_async blocks bundler version :/

Thank you!

**Comment by nikolalsvk** [comment]
Thanks for submitting this issue @n-rodriguez! I've fixed it in the new release https://rubygems.org/gems/render_async/versions/2.0.2

**Comment by n-rodriguez** [comment]
Thank you!
