### ISSUE TITLE
Proposal: Allow nonces?

### ISSUE THREAD

**Issue by colinxfleming** [nikolalsvk/render_async#8]
hey, was wondering -- we at DCAF Engineering are interested in using this, but have a pretty strict content security policy that prohibits running inline js without whitelisting it with a sha or a nonce. We was mulling over submitting a PR to this that would take a nonce value as an argument, but wanted to check and make sure this was something you all were interested in first.

If you are, our team can whip something up real quick, if that sounds good to you?

**Comment by nikolalsvk** [comment]
@colinxfleming sure thing, we're already [generating some kind of unique ID](https://github.com/renderedtext/render_async/blob/6ac3e79a6679ea55395c5381f8dedc00ed8bccf4/lib/render_async/view_helper.rb#L7) for the container where content gets loaded, maybe that will help.

I'd love to see a pull request dealing with your problem

**Comment by colinxfleming** [comment]
@nikolalsvk sounds good, I'll whip something up in the near term for your thoughts and feedback. Thanks for the quick response!
