### ISSUE TITLE
Retry render_async after some time

### ISSUE THREAD

**Issue by nikolalsvk** [nikolalsvk/render_async#80]
If request fails and you want to retry it, you should be able to wait for N seconds before firing another request. You can already [retry on failure](https://github.com/renderedtext/render_async#retry-on-failure), but it will emit another request right away.

Inspired by this comment https://github.com/renderedtext/render_async/issues/46#issuecomment-490540355

If you would like to see this request, please 👍 this issue.

**Comment by vanboom** [comment]
An event-based retry or reload feature would be nice to have.  In my app which is very interactive, there are many events that require partial updates of the screen after some user editing of records.  The ability to manually trigger a reload of a partial that contains a data table would be awesome.   I.e. repeat the original render_async that the loaded the partial based on a JS event.   I have made some progress on this -- see my issue #121

**Comment by nikolalsvk** [comment]
Hey, folks! I just released [2.1.7](https://github.com/renderedtext/render_async/releases/tag/2.1.7) version where there is this feature! 🎉 

Try it out and share your thoughts! We also added a [Discord channel](https://discord.gg/SPfbeRm) where you can get help quickly. I'd be happy to see you there as well. 💚
