### ISSUE TITLE
Passing data example does not work

### ISSUE THREAD

**Issue by abrambailey** [nikolalsvk/render_async#97]
From your readme:

```ruby 
<%= render_async users_path,
                 method: 'POST',
                 data: { fresh: 'AF' },
                 headers: { 'Content-Type': 'text' } %>
```

When I tried this, I get:

=> <ActionController::Parameters {"{:fresh"=>">\"AF\"}", "controller"=>"pages", "action"=>"sidebar_ads"} permitted: false>

**Comment by nikolalsvk** [comment]
Hey @abrambailey, thanks for creating an issue.

It looks like you maybe need to [permit `fresh` as a parameter for your controller action](https://api.rubyonrails.org/classes/ActionController/Parameters.html). Are you doing that?

I'm guessing it would be something like this:

```rb
def user_params
  params.require(:user).permit(:fresh, ...)
end
```

**Comment by abrambailey** [comment]
I was not doing this. Actually, I ended up just passing the data through the path like `users_path(fresh: 'AF')` in the end. Not sure why I didn't do that to begin with 😆

**Comment by nikolalsvk** [comment]
Ah OK 😄 Did you still need to permit the attribute you were passing in? (I'm trying to check whether there's actually a bug in the gem with the example you provided in the first comment)

**Comment by abrambailey** [comment]
No, I didn't ... it worked perfectly without needing to permit using my method.

**Comment by nikolalsvk** [comment]
If you're trying to update the user, you probably need to make it like this

```erb
<%= render_async users_path,
                 method: 'POST',
                 data: { user: { fresh: 'AF' } },
                 headers: { 'Content-Type': 'text' } %>
```

**Comment by nicholaswellens** [comment]
I had the same problem, where the params started with eg. `"{:fresh"=>">"AF"}"`. Worked around it by sending in JSON format:

eg.

```
<%= render_async users_path,
                 method: 'POST',
                 data: { fresh: 'AF' }.to_json,
                 headers: { 'Content-Type': 'application/json' } %>
```
